### ISSUE TITLE
We would like to use your repository, but we have some issues to resolve.

### ISSUE THREAD

**Issue by Philliec459** [adriangrepo/qreservoir#3]
We are missing some statics files

**Comment by adriangrepo** [comment]
Can you specify which static files in particular you are looking for. It's been quite a while since I worked on this.

**Comment by Philliec459** [comment]
Hi Adrian,

Let me run the program and send you the messages that I am getting. It is not recognizing statics which I have no idea of what that is.  Let me  send you the error messages.

Best Regards, 
 
_______________________________
 
E. Craig Phillips
Petrophysicist, CBPC
 









459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
craig@cbpetro.com
www.cbpetro.com
 
The information contained in this electronic message is confidential, it constitutes a profesional and/or industrial secret in terms of the current legislation, and is intended for its recipient only. If you receive this message by mistake or if you are not the recipient thereof, please notify the sender and destroy it.

La informacion contenida en este mensaje de datos es confidencial, constituye un secreto industrial y/o profesional en terminos de la legislacion vigente y se encuentra dirigida exclusivamente al destinatario indicado en dicho mensaje. Si usted recibe esta informacion por error o si usted no es el destinatario del mensaje, favor de notificar al emisor, y destruyalo.



On Jan 12, 2020, at 7:36 AM, Adrian G <notifications@github.com> wrote:

Can you specify which static files in particular you are looking for. It's been quite a while since I worked on this.

**Comment by Philliec459** [comment]
Hi Adrian,


I really like what you have in qreservoir. It is exactly what I was hoping to work with and expand upon to fit my needs. Unfortunately, I cannot get it to work. Thank you for your reply. 

I am running main.py and not able to  see any statics errors now, but then nothing else happens or I get the following error message now. At one time it was a Statics error, but not any more. Sometimes if I run the program again it looks like it is creating a db too, and then nothing.  

runfile('C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master/main.py', wdir='C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master')
2020-01-12 14:33:41,412 - DEBUG - __main__ - main - setWindowSize - 131 - --setWindowSize() number of screens: 1
2020-01-12 14:33:42,475 - DEBUG - console - logsettingstoolbar - initUI - 117 - --initUI() showToolbar.emit()
2020-01-12 14:33:42,475 - DEBUG - __main__ - main - connectSlots - 313 - >connectSlots
2020-01-12 14:33:42,522 - DEBUG - __main__ - main - startDatabase - 420 - >>startDatabase()
2020-01-12 14:33:42,522 - DEBUG - console - databasemanager - checkDBExists - 75 - No database named: sqlite:////tmp/pyqr.db
Traceback (most recent call last):

  File "<ipython-input-1-8a6d672c0461>", line 1, in <module>
    runfile('C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master/main.py', wdir='C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master')

  File "C:\Users\craig\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\craig\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master/main.py", line 473, in <module>
    window = MainApp()

  File "C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master/main.py", line 102, in __init__
    self.startDatabase()

  File "C:/Users/craig/Documents/Python/Odds_and_Ends/src/qreservoir-master/main.py", line 421, in startDatabase
    if not DM.init_db():

  File "C:\Users\craig\Documents\Python\Odds_and_Ends\src\qreservoir-master\db\databasemanager.py", line 61, in init_db
    self.base.metadata.create_all(bind=self.engine)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 4304, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2045, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:

  File "C:\Users\craig\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2037, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2279, in _wrap_pool_connect
    e, dialect, self

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2275, in _wrap_pool_connect
    return fn()

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\impl.py", line 238, in _do_get
    return self._create_connection()

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)

  File "C:\Users\craig\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)

OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)




Best Regards, 
 
_______________________________
 
E. Craig Phillips
Petrophysicist, CBPC
 









459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
craig@cbpetro.com <mailto:craig@cbpetro.com>
www.cbpetro.com
 
The information contained in this electronic message is confidential, it constitutes a profesional and/or industrial secret in terms of the current legislation, and is intended for its recipient only. If you receive this message by mistake or if you are not the recipient thereof, please notify the sender and destroy it.

La informacion contenida en este mensaje de datos es confidencial, constituye un secreto industrial y/o profesional en terminos de la legislacion vigente y se encuentra dirigida exclusivamente al destinatario indicado en dicho mensaje. Si usted recibe esta informacion por error o si usted no es el destinatario del mensaje, favor de notificar al emisor, y destruyalo.



On Jan 12, 2020, at 7:36 AM, Adrian G <notifications@github.com <mailto:notifications@github.com>> wrote:

Can you specify which static files in particular you are looking for. It's been quite a while since I worked on this.

**Comment by adriangrepo** [comment]
The way I coded it I had the db manager inheriting from QObject: DatabaseManager(QObject). I no longer have access to a setup with PyQt installed and from memory was a time consuming process to install it.

I will dig around to see if I can find an old copy of a sqlite database that I could add to the repo but may take a week or so.

Are you able to de-couple the db setup from PyQt?- will make things easier to debug.

Note I added an example file for the statics folder, which should give you something to expand upon.

**Comment by Philliec459** [comment]
I have been going over the error files and maybe the following line could be the issue????


2020-01-14 20:16:01,934 - DEBUG - __main__ - main - setWindowSize - 131 - --setWindowSize() number of screens: 1
2020-01-14 20:16:03,136 - DEBUG - console - logsettingstoolbar - initUI - 117 - --initUI() showToolbar.emit()
2020-01-14 20:16:03,136 - DEBUG - __main__ - main - connectSlots - 313 - >connectSlots
2020-01-14 20:16:03,136 - DEBUG - __main__ - main - startDatabase - 420 - >>startDatabase()
2020-01-14 20:16:03,136 - DEBUG - console - databasemanager - checkDBExists - 75 - No database named: sqlite:////tmp/pyqr.db

**Comment by adriangrepo** [comment]
The code is failing in databasemanager.py:

When the follwing is called:

    def init_db(self):
        ''' Create the database and tables, returns without creating anything if db exists and can't delete it'''
        # initialisation required for object inheritance
        QObject.__init__(self) 
        if self.checkDBExists():

then the code below is run and kills app when cant find the db.

    def checkDBExists(self):
        ''' Returns True if db exists '''
        try:

            open(AppSettings.QR_DATABASE_NAME)
            logger.debug("Database: "+str(self.host)+" already exists")
            return True
        except IOError as e:
            if e.errno == 2: # No such file or directory
                logger.debug("No database named: "+str(self.host))
                return False
            else: # permission denied or something else?
                logger.error(str(e))
                return False

To get running initially, comment out the following in init_db()
        if self.checkDBExists():
            if not self.deleteDB():
                return False

Then a new database will be created, and you should be able to then add the code above back in. Im not sure why the .open method dies - maybe you are running this on windows? and it doesn't like the slashes in appsettings:

    DATABASE_PROTOCOL = "sqlite:///"
    QR_DATABASE_NAME = "/tmp/pyqr.db"

If that is the case, one way to fix this is use Pathlib and replace the hard coded / with Paths

eg:

from pathlib import Path

filename = Path("source_data/text_files/raw_data.txt")

**Comment by Philliec459** [comment]
I have tried all of the above without success. I am on windows and I tried Path. Then there is a problem 

host =...DATABASE_PROTOCOL +....QR_DATABASE_NAME

saying something about windowspath error.

The problem is there is no database named: sqlite:\tmp\pyqr.db

If I could find the database being created, then maybe I could hard code all of this. I think the database is named pyqr.db. I have searched and searched for a file called pyqr.db, but I find nothing.

**Comment by Philliec459** [comment]
I got it to create a pyqr.db by changing 

QR_DATABASE_NAME = "/pyqr.db"

and avoid creating a tmp directory. Now I have some other issues, but I am past this one

**Comment by Philliec459** [comment]
OK, I am trying to load a las file, but it does not read it. I see in your code that you have an example:

fileName = dialog.getOpenFileName(self, "/home/a/TestData/antelope-1_comp.las", "/home/a/TestData/antelope-1_comp.las")

maybe if I started from your las. I have tried 2 different las files and I get the following error:
 
ArgumentError: Textual SQL expression 'well' should be explicitly declared as text('well')

and, I have changed the 
fileName = dialog.getOpenFileName(self, "/home/a/TestData/antelope-1_comp.las", "/home/a/TestData/antelope-1_comp.las")

to

fileName = dialog.getOpenFileName(self, "1.las", "1.las")

I am not sure why it should be listed twice.

**Comment by Philliec459** [comment]
I am also missing your toolbar
